export const UserData = [
  {
    id: 1,
    year: 1990,
    useGain: "Geilenkirchen Air Base",
    userLost: "mdober0",
  },
  {
    id: 2,
    year: 2012,
    useGain: "Cluff Lake Airport",
    userLost: "mfanthom1",
  },
  {
    id: 3,
    year: 1992,
    useGain: "Baytown Airport",
    userLost: "abarrett2",
  },
  {
    id: 4,
    year: 2000,
    useGain: "Taszár Air Base",
    userLost: "bbetteridge3",
  },
  {
    id: 5,
    year: 1999,
    useGain: "Alma Airport",
    userLost: "cpexton4",
  },
  {
    id: 6,
    year: 2006,
    useGain: "Greenlee County Airport",
    userLost: "dbraisher5",
  },
  {
    id: 7,
    year: 2003,
    useGain: "Satna Airport",
    userLost: "dsimmonds6",
  },
  {
    id: 8,
    year: 2007,
    useGain: "Bomai Airport",
    userLost: "adobbings7",
  },
  {
    id: 9,
    year: 2000,
    useGain: "Regional Orlando Villas Boas Airport",
    userLost: "cbrymham8",
  },
  {
    id: 10,
    year: 2008,
    useGain: "Colorado Plains Regional Airport",
    userLost: "sravenscroftt9",
  },
  {
    id: 11,
    year: 2011,
    useGain: "Cleve Airport",
    userLost: "mnewtona",
  },
  {
    id: 12,
    year: 2006,
    useGain: "Hancock County-Bar Harbor Airport",
    userLost: "zdevereuxb",
  },
  {
    id: 13,
    year: 2001,
    useGain: "Paruma Airport",
    userLost: "tbearhamc",
  },
  {
    id: 14,
    year: 1994,
    useGain: "Paso Robles Municipal Airport",
    userLost: "ccrummyd",
  },
  {
    id: 15,
    year: 2001,
    useGain: "Codrington Airport",
    userLost: "ecorsore",
  },
  {
    id: 16,
    year: 1999,
    useGain: "K. D. Matanzima Airport",
    userLost: "rmaplesdenf",
  },
  {
    id: 17,
    year: 2002,
    useGain: "Batuna Aerodrome",
    userLost: "ctresslerg",
  },
  {
    id: 18,
    year: 2004,
    useGain: "Roosevelt Municipal Airport",
    userLost: "jhagerghamh",
  },
  {
    id: 19,
    year: 1999,
    useGain: "Kiunga Airport",
    userLost: "aperigoi",
  },
  {
    id: 20,
    year: 1996,
    useGain: "Eliye Springs Airport",
    userLost: "gmalpasj",
  },
];
